### ISSUE TITLE
Not dark-theme friendly.

### ISSUE THREAD

**Issue by moon9090** [Slavrick/GodotScript4Notepadplusplus#1]
![GodotScript4_DarkThemeIssue](https://github.com/user-attachments/assets/d88e6d90-f510-4da5-bbe8-6d7788f7d3d5)

**Comment by Slavrick** [comment]
Thanks for the dark theme. For anyone with issues in the furture, Notepad++ allows you to customize the user defined languages, so you will be able to change the keyword color of anything to anything else. I really should change the background color on the main theme to transparent.
